-- walmart db
-- load staging table

-- DROP TABLE temp_orders;
CREATE TABLE IF NOT EXISTS temp_orders (
    category varchar(50),
    city varchar(75),
    country varchar(75),
    customer_id varchar(25),
    customer_name varchar(75),
    discount numeric,
    market varchar(50),
    记录数 int,
    order_date timestamp,
    order_id varchar(50),
    order_priority varchar(50),
    product_id varchar(50),
    product_name varchar(200),
    profit float,
    quantity int,
    region varchar(50),
    row_id int,
    sales float,
    segment varchar(50),
    ship_date timestamp,
    ship_mode varchar(50),
    ship_cost float,
    "state" varchar(100),
    subcategory varchar(50),
    "year" int,
    market2 varchar(50),
    weeknum int
);

COPY temp_orders
FROM :'localpath'
( FORMAT CSV, DELIMITER(E'\t'), HEADER );

-- DROP TABLE public.stg_orders
CREATE TABLE IF NOT EXISTS stg_orders (
    id serial PRIMARY KEY,
    category varchar(50),
    city varchar(75),
    country varchar(75),
    customer_id varchar(25),
    customer_name varchar(75),
    discount numeric,
    market varchar(50),
    记录数 int,
    order_date timestamp,
    order_id varchar(50),
    priority varchar(50),
    product_id varchar(50),
    product_name varchar(200),
    profit float,
    quantity int,
    region varchar(50),
    row_id int,
    sales float,
    segment varchar(50),
    ship_date timestamp,
    ship_mode varchar(50),
    ship_cost float,
    "state" varchar(100),
    subcategory varchar(50),
    "year" int,
    market2 varchar(50),
    weeknum int,
    file_id int,
    insert_date timestamp
);

INSERT INTO stg_orders(
    category, 
    city, 
    country,
    customer_id,
    customer_name,
    discount, 
    market,   
    记录数,      
    order_date,
    order_id,
    priority,
    product_id,
    product_name,
    profit,
    quantity, 
    region,  
    row_id,  
    sales, 
    segment,
    ship_date,
    ship_mode,
    ship_cost,
    state,
    subcategory,
    year, 
    market2, 
    weeknum,
    file_id,
    insert_date
)
SELECT
    category, 
    city, 
    country,
    customer_id,
    customer_name,
    discount, 
    market,   
    记录数,      
    order_date,
    order_id,
    order_priority,
    product_id,
    product_name,
    profit,
    quantity, 
    region,  
    row_id,  
    sales, 
    segment,
    ship_date,
    ship_mode,
    ship_cost,
    state,
    subcategory,
    year, 
    market2, 
    weeknum,
    1 as file_id,
    now() as insert_date 
FROM temp_orders;
